FROM golang:1.25-alpine

WORKDIR /app

# Copy go.mod and go.sum first for better caching
COPY go.mod go.sum ./
RUN go mod download

# Copy shared packages
COPY ../database /app/database
COPY ../pkg /app/pkg
COPY ../middleware /app/middleware

# Copy product service code
COPY . .

# Build the application
RUN go build -o product-service ./cmd/main.go

EXPOSE 8082

CMD ["./product-service"]