version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: product_catalog
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  category-service:
    build: .
    ports:
      - "8081:8081"
    environment:
      DATABASE_URL: "host=postgres user=postgres password=postgres dbname=product_catalog port=5432 sslmode=disable"
      PORT: "8081"
    depends_on:
      - postgres

volumes:
  postgres_data: